/*----------------------------------------------------------------*/
/*
    Program to read TC2000 data (binary)
    Author: Nick Schmitz
    Date: 11/23/96

Command Line:

    C:>STKSCN XYZ DATE DBG

Overview:
 Program reads TC2k data from Explicit location (f:\tc2000cd\x\xyz.ndx)
 or from name generated by adding to XYZ argument passed on Command line
    C:\tc2000\data\x\XYZ.ndx

 Second argument is date (960907) for beginning of analysis period.

 Suggestion: use 1 year for Osc finding, <90 day for Ramp detection.

 Third & fourth argument is debug level (presence detection).

 Trades are initiated using MACD trading (5/15 day) crossing detect.

 Buy is at low point, sell is at high. Must be $1.50 apart & $100
 commission charged. $5k investment used for share calculations.

*/
/*----------------------------------------------------------------*/
/*
 Dog: (any one fails)  - Flags: *d*. & *d*!
    1. Low volume (mavl<2k shares/day)
    2. Low price (gmin<$0.35)
    3. Continuous run of decreasing ma5's (82% of 8 day samples)

 Ramp: (All must hold) - Flags: *r*. & *r*!
    1. Adequate volume (mavl>10k shares)
    2. Ramp rate of $23/day
    3. Continuous run of increasing ma5's (56% of 8 day samples)
    4. Swing of $1.50 from buy/sell

 Osc: (All must hold) - Flags: *o*. & *o*!
    1. Adequate volume (mavl>10k shares)
    2. # of trades in period >3
    3. Ramp rate of $40/day
    4. Trading balance (without largest trade) >$4k
    5. Range of prices: (gmin>$0.50, gmax<$25), ratio <5:1)
    6. Ratio of largest trade to avg trade <5:1
*/
/*----------------------------------------------------------------*/

#include <stdio.h>
#include <math.h>
#include <alloc.h>/**/

#define MAX_LINE_LENGTH  120	/* unused /**/

float high,  low,  cls, vol;            /* tc2k data /**/
float mavl, ma5, ma20, tprc, lstp, lcse, date;
float
    rmin, rmax,  /* Relative max & min - max/min date /**/
    tbal, tdat,	 /* Trading balance & trading days /**/
    shar, bprc,  /* Shares, buy price, buy date /**/
    bdat, mdat,  /* Buy date, min/max date /**/
    styp, dflg,	 /* Stock type, direction Flag /**/
    omav,	  	 /* Old moving average /**/
    tstp, tevl,  /* total stk type, total evals /**/
    mxtr, ttrd,	 /* Max trade, this trade profit /**/
    gmin, gmax,  /* Global max & min /**/
    lmin, temp,	 /* local min /**/
    vthl, vdrp,  /* Volatility threshold trading /**/
    avdf, dlta,  /* Abs avg dif, avg daily prc /**/
    hldf, ccdf;	 /* Abs differences - High/Low, Close/Close /**/

int   dbg, ntrd;	 /* Debug Flag, Number of trades /**/

/*----------------------------------------------------------------*/
/*
	Read stock data & compute volume & price data
*/
/*----------------------------------------------------------------*/

double msb2d (long ii) /* Convert number format /**/
{
    char foo[4];
    char *p;
    long expo,j,k;
    int  sign;
    double x,rslt;

    p=&ii;
    expo=p[3]+104; /* -$98 /**/
    if (expo>128) expo=expo-256;
    if (expo==104) expo=-152;
    k=1;
    sign=1;
    if (ii & 1<<23) sign=-1;

    j=ii | 1<<23; 		/* $0.80.00.00 /**/
    j= j & ((1<<24)-1); 	/* $0.FF.FF.FF /**/

/*----------------------------------------------------------------*/
    if (dbg>7) printf(" %d %d %d %d \n",p[0], p[1], p[2], p[3]);/**/
    if (dbg>7) printf(" %12ld %12ld    %d %d ",ii, j, sign, expo);/**/

    if ((expo<=32) && (expo>-32))
        {
        if (expo>=0) x=k<< expo;
                else x=k<<-expo;
        rslt=sign*j/x;
        }
      else
        {
/*        x=exp(expo*log(2.0));
        rslt=sign*j*x;/**/
        rslt=0.0;
        }
     if (dbg>7) printf("%12.3f %12.3f \n",x,rslt);/**/
     return(rslt);
}

/*----------------------------------------------------------------*/
void rd_tc2k(int argc, char *argv[])
{
     char  cbuf[25];
     int   jbuf[11];
     long  lbuf[6];
     float v[6];

     int j,k,m,q;
	 int r,s;
	 int ln, lnc, tmp;
	 char a_str[256], b_str[256], c_str[256];
	 FILE *fp;

/*----------------------------------------------------------------*/
/*     printf("%s \n",*argv);/**/
/*     printf("%s \n",*++argv);/**/
    *++argv;/**/    /* Skip Prog Name */

/*----------------------------------------------------------------*/
/*   for (k=1; k<60; k++) printf("*");   printf(" \n"); /**/
/*----------------------------------------------------------------*/
/*
	File access stuff - handle errors & exit
*/
	 if(argc==1) {
		  printf("Need file name \n");
/*		  exit(1); /**/
		  }
         strcpy(a_str,*argv);
	 if((argc>1) && (fp = fopen(a_str, "rb")) == NULL) {/**/

		  cbuf[0]=a_str[0];  cbuf[1]=0;

		  strcpy(a_str,"e:\\tc2000cd\\");/**/
/*		  strcpy(a_str,"c:\\tc2000\\data\\");/**/
/*		  strcat(a_str,cbuf);
                  strcat(a_str,"\\");/**/

                  strcat(a_str,*argv);

		 q=0;
		 for (k=0; a_str[k]; k++) { if (a_str[k]=='.') q=k; }
                 if (q==0) strcat(a_str,".ndx");/**/
                 if (dbg>2) printf("%s\n",a_str);

  	          if((argc>1) && (fp = fopen(a_str, "rb")) == NULL) {
		       printf("Cannot open file %s %s\n",*argv,a_str);
/*		       exit(1);/**/
                      }
  } /* open fail/**/
/*----------------------------------------------------------------*/
 vthl=-1.0;
 if(argc>2){  /* pick up date from command line /**/
        *++argv;/**/    /* Skip stk sym */
        sscanf(*argv, "%f %[^\n]s", &date, &b_str); /**/
/*   printf("C %s %f  \n ",*argv, date);/**/

        if(argc>3){  /* pick up date from command line /**/
          *++argv;/**/    /* Skip stk sym */
          sscanf(*argv, "%f %[^\n]s", &vthl, &b_str); /**/
          vthl=2.0*vthl;
/*   printf("C %s %f  \n ",*argv, vthl);/**/
          }
     } else {date=0.0;}

   q=0;
   for (k=0; a_str[k]; k++) { if (a_str[k]=='\\') q=k; }
   if (q>0) q++;

   for (k=0; a_str[q]!='.' && a_str[q]; k++) c_str[k]=a_str[q++];
   c_str[k++]=0;/**/
/*----------------------------------------------------------------*/

/*
    printf("C %d   ",sizeof(cbuf));
    printf("J %d   ",sizeof(jbuf));
    printf("L %d \n",sizeof(lbuf));/**/

/*
    for (q=0; q<=24; putch('a'+q++)) {};
    printf("\n");/**/

    gmin=999.9;     gmax=0.001;     rmin=999.9;     rmax=0.001;
    tbal=0.001;     shar=0.001;     bprc=0.001;     styp=0.0;
    ma5=-1.0;       ma20=-1.0;      omav=-1.0;      mavl=-1.0;
    dflg=1.0;       ntrd=001;       tdat=0.001;     bdat=0.001;
    tstp=0.001;     tevl=0.001;     mxtr=0.001;     ttrd=0.001;
    lmin=999.9;     hldf=0.001;     ccdf=0.001;     avdf=0.001;
    lcse=-1.0;      dlta=-1.0;

/*----------------------------------------------------------------*/
    fread(&cbuf,sizeof(cbuf)-1,1,fp); 	/* read stock name */
    cbuf[24]=0;
    lnc=0;
    if (dbg>2) printf("%s\"%s\"\n",a_str,cbuf);/**/
    if (dbg>4) printf("\"date\",\"open\",\"high\",\"low\",\"close\",\"vol\"\n");

    fread(&jbuf,sizeof(jbuf),1,fp); 	/* skip data flags */
    fread(&q,sizeof(q),1,fp);   /* Some off-by-one problem */

    if (dbg>7) for (q=0; q<=10; q++) printf("%8d ",jbuf[q]);
    if (dbg>7) printf("\n");

/*----------------------------------------------------------------*/
    for (ln=1; ln<12510 && feof(fp)==0; ln++)  /* daily data */
       {
    	fread(&lbuf,sizeof(lbuf),1,fp);

        if (dbg>7) for (q=0; q<=5; q++) printf("%10ld",lbuf[q]);
        if (dbg>7) printf("%d \n",ln);/**/

        for (q=0; q<=5; q++) v[q]=msb2d(lbuf[q]);

/*
       if (dbg>2) printf("%6.0f,%6.3f,%6.3f,%6.3f,%6.3f,%6.0f\n",
           v[0],        v[5], v[1], v[2],v[3],  v[4]*100);
/* Format: date-YYMMDD, open, high, low, close, vol */

        vol=v[4]*100;		/* Data for analysis /**/
        high=v[1];
        low=v[2];
        strcpy(b_str,cbuf);
/*----------------------------------------------------------------*/
   if (mavl<0.0) { mavl=vol;}  else { mavl=(11*mavl+vol)/12.0;}
   if ((vol>0.0) && (v[0]>date)){
/*
        if (dbg>2) printf("%6.0f,%6.3f,%6.3f,%6.3f,%6.3f,%6.0f\n",
           v[0],        v[5], v[1], v[2],v[3],  v[4]*100);/**/

       tprc=(high+low)/2.0;
       if (omav<0.0) { omav=tprc;} else if (fmod(v[0],8.0)<0.9) { omav=ma20; }
       if (ma5<0.0)  { ma5 =tprc;} else { ma5 =( 3*ma5 +tprc)/ 4.0;}
       if (ma20<0.0) { ma20=tprc;} else { ma20=(19*ma20+tprc)/20.0;}
       if (lcse<0.0) {lstp=tprc;  lcse=v[3];}
       lnc++;

       avdf=avdf+fabs(ma20-tprc)/ma20;
       vdrp=100.0*(lcse-v[3])/lcse;
       if ( ((ma5>ma20) && (dflg<0.0) && (vthl<0.0))
          || ((vdrp<-vthl) && (vthl>0.0)) )
          { /* Buy condition /**/
/*        if (dbg>2) printf("%6.0f,%6.3f,%6.3f, %6.3f,%6.3f,v\n",
            v[0], tprc, ma5, ma20, rmin);/**/

          rmax=0.0;
          if (rmin<900) { shar=5000.0/rmin;
            	bprc=rmin; bdat=mdat;
            } else { shar=0.0; }
          if (dbg>2) printf("-- %6.0f,%6.0f,%6.3f,%6.3f\n",
            v[0], bdat, bprc, shar);/**/
          }
       else if ( ((ma5<ma20) && (dflg>0.0) && (vthl<0.0))
          || ((vdrp>vthl) && (vthl>0.0)) )
          { /* Sell condition */
          if ((shar>0.0) && ((rmax-bprc)>1.49))
                { ttrd=shar*(rmax-bprc)-100;
          	  if (ttrd>mxtr) { mxtr=ttrd; }
          	  tbal=tbal+ttrd;
          	  tdat=tdat+(mdat-bdat+1);
                  ntrd++;
          	}

          if (dbg>2) printf("%6.0f,  %6.3f,%6.3f,%6.3f, %6.3f,%6.3f,%6.3f,^ \n",
            v[0],   tprc, ma5, ma20,   rmax, bprc, shar);
          if (dbg>2) printf("%6.0f, %6.3f,%6.3f,%6d,  %6.0f,%6.0f,^ \n\n",
            v[0],   tbal, tdat, ntrd, ttrd, mxtr);/**/

          rmin=999.9;  shar=0.0;
          }
       if ((dflg>0.0) && (tprc>rmax)) { rmax=tprc; mdat=ln; }
       if ((dflg<0.0) && (tprc<rmin)) { rmin=tprc; mdat=ln; }
       if (tprc>gmax) { gmax=tprc; }
       if (tprc<gmin) { gmin=tprc; }

/*----------------------------------------------------------------*/
       if ((styp<0.1 ) && (styp>-0.1)) {
        	if (ma20>omav) { styp=1.0; } else {styp=-1.0; } }
       if ((styp>0.1 ) && (ma20<omav)) { styp=0.0; }
       if ((styp<-0.1) && (ma20>omav)) { styp=0.0; }
       if (fmod(v[0],8.0)<0.9) { tstp=tstp+styp;
           if (rmin<lmin) { lmin=rmin;}
           tevl++;
          }
/*----------------------------------------------------------------*/
       if (fmod(v[0],8.0)<0.9)
         if (dbg>2) printf("%6.0f,%6.3f,  %6.3f,%6.3f,  %6.0f,%6.0f,$ \n",
            v[0], tprc,   ma5, ma20,   dflg, styp);/**/
         if (dbg>12) printf("%6.0f,%6.3f,%6.3f,%6.3f,%6.3f,%6.0f\n",
            v[0],        v[5], v[1], v[2],v[3],  v[4]*100);/**/

       hldf=hldf+(high-low)/low;
       ccdf=ccdf+fabs(lcse-v[3])/lcse;
       lstp=tprc;  lcse=v[3];
       if (ma5>ma20) { dflg=1.0; } else { dflg=-1.0; }
     } /* vol>0 /**/
   } /* each day/**/
tprc=lstp;
/*----------------------------------------------------------------*/
/*  printf("%5.2f %4d \n", temp, lnc);/**/
/*----------------------------------------------------------------*/
/* Main output display /**/
/*----------------------------------------------------------------*/

  if ((shar>0.0) && ((rmax-bprc)>1.49))
       { ttrd=shar*(rmax-bprc)-100;
      	  tdat=tdat+(mdat-bdat+1);
          ntrd++;
/* 	  printf("%6s,*o*,\n", c_str);/**/
       	}

   if (ntrd>0) temp=mxtr/(tbal/ntrd);

/*----------------------------------------------------------------*/
/* Volatilty */
/*----------------------------------------------------------------*/

   avdf=100.0*avdf/lnc;
   hldf=100.0*hldf/lnc;
   ccdf=100.0*ccdf/lnc;
   if (dbg>1) printf("%6s,%6.3f,%6.3f,%6.3f,  %8.2f,%10.0f,*v*",
     c_str,  avdf,hldf,ccdf, gmin, mavl);/**/

   if (( (hldf>2.8) || (ccdf>1.7) )
      && (gmin>10.0) && (mavl>99999.9) )
   {
     if (dbg>1) {
     	printf("!\n");
	printf("%6s,*v*.\n", c_str);
	} else printf("\\%c,%6s,*v*.\n", c_str[0],  c_str);
   } else if (dbg>1) printf("\n");

   if (dbg>1) printf("%6s,%7.0f,%7.2f,%6.0f, D/T:, %4.0f,%4d,%6.2f,*x*",
       c_str,   tbal,tbal/tdat,mxtr,  tdat,ntrd,temp);/**/

   if  ( (tdat>0.0) && (ntrd>3) && ((tbal-mxtr)>2999.9)
    && (temp<5.0) && ((tbal/tdat)>20.0) && ((gmax/gmin)<5.0)
    && (( (hldf>2.8) || (ccdf>1.7) ) && (gmin>10.0) && (mavl>99999.9) ) )
   {
     if (dbg>1) {
     	printf("!\n");
	printf("%6s,*x*.\n", c_str);
	} else printf("\\%c,%6s,*x*.\n", c_str[0],  c_str);
   } else if (dbg>1) printf("\n");

/*----------------------------------------------------------------*/
/* OSC */
/*----------------------------------------------------------------*/

   if (dbg>1) printf("%6s,%7.0f,%7.2f,%6.0f, D/T:, %4.0f,%4d,%6.2f,*o*",
       c_str,   tbal,tbal/tdat,tbal/ntrd,  tdat,ntrd,temp);/**/

   if  ( (tdat>0.0) && (ntrd>3) && ((tbal-mxtr)>3999.9)
    && (temp<5.0) && ((tbal/tdat)>40.0) && ((gmax/gmin)<5.0)
   	&& (gmax<25.0) && (gmin>0.50) && (mavl>9999.9) )
   {
     if (dbg>1) {
     	printf("!\n");
	printf("%6s,*o*.\n", c_str);
	} else printf("\\%c,%6s,*o*.\n", c_str[0],  c_str);
   } else if (dbg>1) printf("\n");

/*----------------------------------------------------------------*/

   tbal=5000.0/lmin*(rmax-lmin);
   tdat=lnc+0.001;
/*   printf("..\n");/**/

/*----------------------------------------------------------------*/
/* RAMP */
/*----------------------------------------------------------------*/

   if (dbg>1) printf("%6s,%7.0f,%6.2f, $B/S:, %6.2f,%6.2f,%4.0f,*r*",
       c_str,   tbal,tbal/tdat, lmin,rmax, tdat);/**/

   if ( ((tstp/tevl)>0.55) && ((tbal/tdat)>22.9) && (mavl>9999.9)
       && ((rmax-lmin)>1.49) && ((tbal/tdat)<500) )
   {
     if (dbg>1) {
     	printf("!\n");
	printf("%6s,*r*.\n", c_str);
	} else printf("\\%c,%6s,*r*.\n", c_str[0],  c_str);
   } else if (dbg>1) printf("\n");

/*   printf("%6.2f\n",(tstp/tevl));/**/

/*----------------------------------------------------------------*/
/* DOG */
/*----------------------------------------------------------------*/

   if (dbg>1) printf("%6s,%4.0f,%4.0f,%8.0f, Rng:, %6.2f,%6.2f,%5.1f,*d*",
     c_str,  tstp,tevl,mavl, gmin,gmax, gmax/gmin);/**/

   if ( ((tstp/tevl)<-0.81) ||
      (gmax>189.0) || (gmin<0.35) || (mavl<1999.9) )
   {
     if (dbg>1) {
     	printf("!\n");
	printf("%6s,*d*.\n", c_str);
	} else printf("\\%c,%6s,*d*.\n", c_str[0],  c_str);
   } else if (dbg>1) printf("\n");

/*----------------------------------------------------------------*/
} /* rdtc/**/
/*----------------------------------------------------------------*/
main(int argc, char *argv[]) /* stkscn file_name date dbg1 dbg2 /**/
{
      dbg=0;
      if(argc>4) { dbg=3; } else
         if(argc>3) { dbg=2; } else { dbg=0; }
      rd_tc2k(argc, argv);
}
/*----------------------------------------------------------------*/
