Nick, I use a single trigger mechanism for my software methodolgy.
Basically, what I do is study a market segment (my speciality is the High
Tech sector) and apply certain rules to buy/sell orders. The trigger is
nothing complex, just a percentage drop. The software I wrote checks
historical prices for optimum gains using percentage drops/increases. It's
not snazzy, and does not even take into account the market as a whole, but
it has been quite effective over the past few months in allowing me to
triple the normal return on a stock (I use Intel, but other stocks are just
as good, if studied carefully). 

I'm so confidant of this system that I'm going to be releasing it to the
public shortly (for a price, of course). This, combined with my relentless
study of the technology sector (I'm a software engineer), will enable me
(and others) to reap profits from the Tech sector that far exceed the Dow
climb.

I'm attaching the Alpha version of my software (along with the
documentation) for you to check out. The documentation is a Microsoft Word
file (WIZARD.DOC) that gives a glimpse into how I think. The .EXE file
(WIZARD.EXE) is a basic DOS program that I slapped together in two
evenings. I plan to upgrade this to a Windows version soon, and I'll be
adding substantially to the output capabilities. Let me know what you
think. But remeber, this is all pre-release Alpha software.

-Cliff
cliffw1@airmail.net


----------
> From: Nick Schmitz <nick.schmitz@amd.com>
> To: cliffw1@airmail.net
> Cc: nick.schmitz@amd.com
> Subject: Re: INTEL'S PRICE AND FUTURE
> Date: Sunday, December 22, 1996 2:52 AM
> 
> Cliff,
> 
> > If anybody's even
> > remotely interested in software such as this (or custom-written
software of
> > this nature), email me.
> 
> You bet I'm interested.
> 
> I've been looking into building a trading system using multiple
> triggers (stoc, rsi & macd) for a few months now. I use Delphi
> for creating the program & TC2k/Pro for my data source. I'd
> like to have a discussion of how you measure results & discount
> overall mkt trends. Thanks for your reply.
> 
> Nick Schmitz